version: "3.9"

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5342"
    command: -c "config_file=/var/app/my-postgres.conf"
    volumes:
      - ./postgresql:/var/app
